admin:
  address: 0.0.0.0
  enabled: true
  port: 5201
  publicURL: http://127.0.0.1:5201
debug:
  port: 6060
event:
  dbevents:
    bufferSize: 10000
http:
  address: 0.0.0.0
  port: 5001
  publicURL: http://127.0.0.1:5001
log:
  level: debug
metrics: {}
namespaces:
  default: default
  predefined:
  - defaultKey: 0xa4787c8093a884d8f43dc0e23346cab2bd6dea9e
    description: Default predefined namespace
    multiparty:
      contract:
      - firstEvent: "0"
        location:
          address: 0xeec5cc36e6f9062c220341308330b8637997604b
        options: {}
      enabled: true
      node:
        name: node_4282b6
      org:
        key: 0xa4787c8093a884d8f43dc0e23346cab2bd6dea9e
        name: org_4282b6
    name: default
    plugins:
    - database0
    - blockchain0
    - dataexchange0
    - sharedstorage0
    - erc20_erc721
plugins:
  blockchain:
  - ethereum:
      ethconnect:
        topic: "1"
        url: http://evmconnect_1:5008
    name: blockchain0
    type: ethereum
  database:
  - name: database0
    sqlite3:
      migrations:
        auto: true
      url: /etc/firefly/db/sqlite.db?_busy_timeout=5000
    type: sqlite3
  dataexchange:
  - ffdx:
      url: http://dataexchange_1:3000
    name: dataexchange0
    type: ffdx
  sharedstorage:
  - ipfs:
      api:
        url: http://ipfs_1:5001
      gateway:
        url: http://ipfs_1:8080
    name: sharedstorage0
    type: ipfs
  tokens:
  - fftokens:
      url: http://tokens_1_0:3000
    name: erc20_erc721
    type: fftokens
spi:
  address: 0.0.0.0
  enabled: true
  port: 5201
  publicURL: http://127.0.0.1:5201
ui:
  path: ./frontend
