log:
    level: debug
connector:
    url: http://geth:8545
persistence:
    leveldb:
        path: /evmconnect/leveldb
ffcore:
    url: http://firefly_core_2:5002
    namespaces:
        - default
confirmations:
    required: 0
policyengine.simple:
    fixedGasPrice: 0
    gasOracle:
        mode: fixed
api:
    port: 5008
    address: 0.0.0.0
    publicURL: http://127.0.0.1:5302
