log:
  level: debug
debug:
  port: 6060
http:
  port: 5000
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5000
admin:
  port: 5101
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5101
  enabled: true
spi:
  port: 5101
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5101
  enabled: true
metrics: {}
ui:
  path: ./frontend
event:
  dbevents:
    bufferSize: 10000
plugins:
  database:
  - name: database0
    type: sqlite3
    sqlite3:
      url: /etc/firefly/db/sqlite.db?_busy_timeout=5000
      migrations:
        auto: true
  blockchain:
  - name: blockchain0
    type: ethereum
    ethereum:
      ethconnect:
        url: http://evmconnect_0:5008
        topic: "0"
  sharedstorage:
  - name: sharedstorage0
    type: ipfs
    ipfs:
      api:
        url: http://ipfs_0:5001
      gateway:
        url: http://ipfs_0:8080
  dataexchange:
  - name: dataexchange0
    type: ffdx
    ffdx:
      url: http://dataexchange_0:3000
  tokens:
  - type: fftokens
    name: erc20_erc721
    fftokens:
      url: http://tokens_0_0:3000
namespaces: null
