log:
  level: debug
debug:
  port: 6060
http:
  port: 5001
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5001
admin:
  port: 5201
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5201
  enabled: true
spi:
  port: 5201
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5201
  enabled: true
metrics: {}
ui:
  path: ./frontend
event:
  dbevents:
    bufferSize: 10000
plugins:
  database:
  - name: database0
    type: postgres
    postgres:
      url: postgres://postgres:f1refly@postgres_1:5432?sslmode=disable
      migrations:
        auto: true
  blockchain:
  - name: blockchain0
    type: ethereum
    ethereum:
      ethconnect:
        url: http://evmconnect_1:5008
        topic: "1"
  sharedstorage:
  - name: sharedstorage0
    type: ipfs
    ipfs:
      api:
        url: http://ipfs_1:5001
      gateway:
        url: http://ipfs_1:8080
  dataexchange:
  - name: dataexchange0
    type: ffdx
    ffdx:
      url: http://dataexchange_1:3000
  tokens:
  - type: fftokens
    name: erc20_erc721
    fftokens:
      url: http://tokens_1_0:3000
namespaces: null
